version: "3.3"

services:
    nginx:
        image: nginx

    php:
        build: ./php
        ports:
        - 3000

    nodejs:
        build: ./nodejs
        ports:
        - 3000

    express:
        build: ./express
        ports:
        - 3000

    go:
        build: ./go
        ports:
        - 3000

    swoole:
        build: ./swoole
        ports:
        - 3000

    laravel:
        build:
            context: ./laravel
            dockerfile: Dockerfile-laravel
        ports:
        - 3000

    octane:
        build:
            context: ./laravel
            dockerfile: Dockerfile-octane
        ports:
        - 3000

    dotnet:
        build: ./dotnet
        ports:
        - 3000

    wrk:
        image: skandyla/wrk
        entrypoint: '/bin/sh'
        stdin_open: true # docker run -i
        tty: true        # docker run -t