FROM phpswoole/swoole:4.7-php8.0-alpine

RUN docker-php-ext-configure pcntl --enable-pcntl && docker-php-ext-install pcntl

# basic laravel requirement
RUN apk add git libzip-dev libxml2-dev \
    && docker-php-ext-configure bcmath \
    && docker-php-ext-install bcmath zip xml

RUN docker-php-ext-install opcache

COPY composer.json composer.lock /var/www/
RUN composer install --no-dev --no-scripts

COPY . /var/www/

RUN composer dumpautoload -o && \
    php artisan config:cache && \
    php artisan route:cache

ENV APP_NAME=Laravel
ENV APP_ENV=production
ENV APP_DEBUG=false
ENV APP_KEY="base64:Ish0RPC6AmMBqcE47DksWJfyy9AXWey22F3ndGetLTg="

EXPOSE 3000
CMD ["php", "artisan", "octane:start", "--host=0.0.0.0", "--port=3000"]